package com.arkea.com.arkea.commons.archetypes.server.commons.memcached;

import java.util.Date;

import org.apache.commons.lang.time.DateUtils;

/**
 * 
 * Detail d'un objet mis en cache
 * 
 * @author  generated by Archetype
 * 
 */
public class CacheBean {

	private String key;      		 // Clé stockée dans le memcached
	private String comment;  		 // Commentaire associé
	private String type;     		 // ID du memcached
	private Date dateEnregistrement; // Date d'enregistrement
	private int ttl;         		 // Duree de stockage

	/**
	 * @param key
	 *            cle
	 * @param comment
	 *            commentaire
	 * @param type
	 *            type
	 * @param timeToLive
	 *            ttl
	 */
	public CacheBean(String key, String comment, String type, int timeToLive) {
		this.key = key;
		this.comment = comment;
		this.type = type;
		this.ttl = timeToLive;
		this.dateEnregistrement = new Date();
	}
	
	/**
	 * 
	 * @return boolean
	 */
	public boolean isAlive(){
		return  getDateExpiration().after(new Date());
	}

	/**
	 * 
	 * @return cle
	 */
	public String getKey() {
		return key;
	}

	/**
	 * 
	 * @return commentaire
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * 
	 * @return type
	 */
	public String getType() {
		return type;
	}

	/**
	 * 
	 * @return date d'enregistrement
	 */
	public Date getDateEnregistrement() {
		return dateEnregistrement;
	}

	/**
	 * 
	 * @return ttl
	 */
	public int getTtl() {
		return ttl;
	}

	/**
	 * 
	 * @return date d'expiration
	 */
	public Date getDateExpiration() {
		return DateUtils.addSeconds(dateEnregistrement, ttl);
	}
	
}
