package com.arkea.com.arkea.commons.archetypes.server.commons.bean;

import javax.servlet.http.HttpSession;

import net.gicm.methode.clientgestioncontexte.bo.ContexteSalarieBean;
import net.gicm.methode.clientgestioncontexte.bo.MapHabilitationBean;
import net.gicm.methode.clientgestioncontexte.servlet.IClientGestionContexteServlet;

import com.google.inject.Inject;
import com.google.inject.Provider;
import com.google.inject.servlet.SessionScoped;

/**
 * Cette classe permet de partager un ensemble de donnnées dans la session de l'utilisateur
 * sur la partie serveur.
 * 
 * @author  generated by Archetype
 *
 */
public class UserSession {

	@Inject Provider<HttpSession> session;
	
	@Inject
	private UserSession() {
	}
	
	//TODO Ajouter les getter et setter des variables partagée sur la partie Serveur
	//    Elles doivent êtres stockées en session et non en local
	// Exemple : 
	//	public String getMaVariable() {
	//		return (String)session.get().getAttribute("maVariable");
	//	}
	//	
	//	public void setMaVariable(String variable) {
	//		session.get().setAttribute("maVariable",variable);
	//	}	
	
	/**
	 * Récupération du code EFS
	 * @return
	 */
	public String getCodeEfsTravail() {
		return (String) session.get().getAttribute("codeEfsTravail");
	}
	
	/**
	 * Mise en session du code EFS
	 * @param cdEfs
	 */
	public void setCodeEfsTravail(String cdEfs) {
		session.get().setAttribute("codeEfsTravail",cdEfs);
	}
	
	/**
	 * Recuperation du code SI
	 * @return
	 */
	public String getCodeSiTravail() {
		return (String) session.get().getAttribute("codeSiTravail");
	}
	
	/**
	 * Mise en session du code SI
	 * @param cdSi
	 */
	public void setCodeSiTravail(String cdSi) {
		session.get().setAttribute("codeSiTravail",cdSi);
	}
	
	/**
	 * recupération du contexte habilitation
	 * @return
	 */
	public MapHabilitationBean getContexteHabilitation() {
		return (MapHabilitationBean) session.get().getAttribute("monContexteHAbilitation");
	}
	
	/**
	 * Mise en session du contexte habilitation
	 * @param variable
	 */
	public void setContexteHabilitation(MapHabilitationBean variable) {
		session.get().setAttribute("monContexteHAbilitation",variable);
	}
	
	/**
	 * Recuperation du contexte Salarie (via gestion de contexte)
	 * @return
	 */
	public ContexteSalarieBean getCtxSalarie() {
		return (ContexteSalarieBean)session.get().getAttribute(IClientGestionContexteServlet.SESSION_TOKEN_CONTEXTE_SALARIE);
	}
	
}
