package com.arkea.com.arkea.commons.archetypes.server.dao.host;

/**
 * 
 * @author generated by Archetype
 *
 */
public class EnteteTechnique {

	protected String codeSI ;
	protected String codeEFS ;
	protected String noSal ;
	protected String noFonction ;
	
	/**
	 *
	 * @return code si
	 */
	public String getCodeSI() {
		return codeSI;
	}
	
	/**
	 * 
	 * @param codeSI code si
	 */
	public void setCodeSI(String codeSI) {
		this.codeSI = codeSI;
	}
	
	/**
	 * 
	 * @return efs
	 */
	public String getCodeEFS() {
		return codeEFS;
	}
	
	/**
	 * 
	 * @param codeEFS efs
	 */
	public void setCodeEFS(String codeEFS) {
		this.codeEFS = codeEFS;
	}
	
	/**
	 * 
	 * @return numero de salarie
	 */
	public String getNoSal() {
		return noSal;
	}
	
	/**
	 * 
	 * @param noSal  numero de salarie
	 */
	public void setNoSal(String noSal) {
		this.noSal = noSal;
	}
	
	/**
	 * 
	 * @return  numero de fonction
	 */
	public String getNoFonction() {
		return noFonction;
	}
	
	/**
	 * 
	 * @param noFonction  numero de fonction
	 */
	public void setNoFonction(String noFonction) {
		this.noFonction = noFonction;
	}
}
