package com.arkea.com.arkea.commons.archetypes.shared.commons;

/**
 * Classe Utilitaire de gestion des habilitations
 *  
 * @author generated by Archetype
 *
 */
public class HabilitationUtils {

	public static final String KEY_HABILITATION = "T-PERSON" ;
	
		public static final int PROFIL_NONHABILITE = 0;
		public static final int PROFIL_CONNECTE = 1;
		public static final int PROFIL_ADMIN = 999;
	
	private HabilitationUtils() {}
	
}
