package com.arkea.com.arkea.commons.archetypes.shared.service;

import com.arkea.commons.ihm.shared.model.ApplicationException;
import com.arkea.com.arkea.commons.archetypes.shared.service.bean.ProfilUserRequestBean;
import com.arkea.com.arkea.commons.archetypes.shared.service.bean.ProfilUserResponseBean;
import com.google.gwt.user.client.rpc.AsyncCallback;
import com.google.gwt.user.client.rpc.RemoteService;
import com.google.gwt.user.client.rpc.RemoteServiceRelativePath;

public class ProfilUserService {

	/**
	 *  Interface Synchrone avec la declaration pour la servlet
	 * @author  generated by Archetype
	 *
	 */
	@RemoteServiceRelativePath("gwt/ProfilUserService")
	public interface Iface extends RemoteService{
		 public ProfilUserResponseBean getProfilUserService(ProfilUserRequestBean entree) throws ApplicationException;
	}
	
	/**
	 * Interface Asynchrone
	 * @author  generated by Archetype
	 *
	 */
	public interface IfaceAsync {
		 public void getProfilUserService(ProfilUserRequestBean entree, AsyncCallback<ProfilUserResponseBean> sortie) throws ApplicationException;
	}

}
